version: "3"
services:
  badapp:
    container_name: badapp
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
volumes:
    db-data:
        driver: local