version: "3"
services:
  badapp:
    container_name: badapp
    image: oursgroumy/badapp
    restart: always
    ports:
      - "80:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
volumes:
    db-data:
        driver: local